(() => {
  const $=s=>document.querySelector(s), reduce=matchMedia('(prefers-reduced-motion: reduce)');
  const labels=['Séries','Films','Explorer','Profil'], icons=['tv-minimal','clapperboard','scan-search','user-round'];
  const variants=[['crystal','Cristal','Une capsule continue.','Verre clair, reflets fins et sélection douce.'],['lilac','Lentille lilas','Le caractère de Nitrate.','Une lentille teintée se déforme légèrement sous le doigt.'],['pebbles','Galets','Quatre touches de verre.','L’onglet actif se soulève ; les autres restent à leur place.']];
  const states=[];let selected=0, candidate=0, fraction=0, demoFrame=0, owner=null;
  function icon(name){return `<i data-lucide="${name}" aria-hidden="true"></i>`;}
  variants.forEach(([type,name,lead,desc],idx)=>{
    const section=document.createElement('section');section.className='variant '+type;
    section.innerHTML=`<header class="variant-head"><span>0${idx+1}</span><h2>${name}</h2></header><div class="phone"><div class="phone-head"><img src="assets/wordmark.svg" alt="Nitrate">${icon('bell')}</div><div class="content"></div><div class="nav-wrap"><nav class="glass-nav" aria-label="Navigation ${name}"><div class="glass-surface"></div><div class="lens"></div>${labels.map((label,i)=>`<button type="button" aria-label="${label} — ${name}" aria-pressed="${i===0}" data-index="${i}" data-preview="${i===0}">${icon(icons[i])}<span>${label}</span></button>`).join('')}<div class="demo-pointer" hidden></div></nav></div></div><p class="variant-note"><strong>${lead}</strong> ${desc}</p><div class="drag-note">Page : Séries</div>`;
    $('#gallery').append(section);const s={section,nav:section.querySelector('nav'),content:section.querySelector('.content'),buttons:[...section.querySelectorAll('nav button')],note:section.querySelector('.drag-note')};states.push(s);
    s.nav.addEventListener('pointerdown',e=>{if(e.button!==0)return;stopDemo();if(owner)return;owner={s,id:e.pointerId};s.nav.setPointerCapture(e.pointerId);e.preventDefault();track(s,e);});
    s.nav.addEventListener('pointermove',e=>{if(owner?.s===s&&owner.id===e.pointerId)track(s,e);});
    s.nav.addEventListener('pointerup',e=>{if(owner?.s!==s||owner.id!==e.pointerId)return;track(s,e);owner=null;commit(candidate);if(s.nav.hasPointerCapture(e.pointerId))s.nav.releasePointerCapture(e.pointerId);});
    const cancel=()=>{if(owner?.s!==s)return;owner=null;preview(selected,selected,false);};
    s.nav.addEventListener('pointercancel',cancel);s.nav.addEventListener('lostpointercapture',cancel);
    s.buttons.forEach((b,i)=>{b.addEventListener('click',e=>{if(e.detail===0){stopDemo();commit(i);}});b.addEventListener('keydown',e=>{if(e.key==='Escape'){owner=null;preview(selected,selected,false);}if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();s.buttons[(i+(e.key==='ArrowRight'?1:3))%4].focus();}});});
  });
  function preview(index,position,dragging){candidate=index;fraction=position;states.forEach(s=>{const cell=(s.nav.clientWidth-(s.section.classList.contains('pebbles')?0:10))/4;s.nav.style.setProperty('--x',`${position*cell}px`);s.nav.style.setProperty('--stretch',dragging&&s.section.classList.contains('lilac')?'1.055':'1');s.nav.style.setProperty('--shine',`${12+position*25}%`);s.nav.classList.toggle('dragging',dragging);s.buttons.forEach((b,i)=>b.dataset.preview=String(i===index));s.note.textContent=dragging?`Page : ${labels[selected]} · relâcher pour ${labels[index]}`:`Page : ${labels[selected]}`;});}
  function track(s,e){const r=s.nav.getBoundingClientRect();if(e.clientY<r.top-20||e.clientY>r.bottom+20)return;const inset=s.section.classList.contains('pebbles')?0:5,cell=(r.width-2*inset)/4;const x=Math.max(0,Math.min(3,(e.clientX-r.left-inset)/cell-.5));const index=Math.max(0,Math.min(3,Math.floor((e.clientX-r.left-inset)/cell)));preview(index,x,true);}
  const titles=['La dernière lumière','Les jours suspendus','Au-delà des étoiles','L’heure bleue','Après la nuit','Le passage'];
  function content(index){
    if(index===3)return `<div class="page-heading"><h3>Profil</h3><span>Ton carnet</span></div><div class="profile-context"><div class="profile-identity"><div class="emoji">🦸</div><div><strong>Tom</strong><small>Membre depuis août 2026</small></div></div><div class="stats-block"><small>TEMPS DE VISIONNAGE ESTIMÉ</small><strong>336j 20h</strong></div><div class="profile-list">Films vus <span>35</span></div><div class="profile-list">Séries suivies <span>173</span></div><div class="profile-list">Épisodes vus <span>14 624</span></div></div>`;
    return `<div class="page-heading"><h3>${labels[index]}</h3><span>${['À reprendre','Ma liste','Découvrir'][index]}</span></div>${index===2?`<div class="search-context">${icon('search')}Rechercher un film, une série</div>`:''}<div class="cards">${titles.map((title,i)=>`<article class="poster" style="--pos:${((i+index)%3)*50}%"><div class="poster-caption"><strong>${title}</strong><small>${index===0?'S02 · E0'+(i+1):index===1?'2025 · 1 h 48':'À découvrir'}</small></div></article>`).join('')}</div>`;
  }
  function commit(index){selected=index;states.forEach(s=>{s.content.innerHTML=content(index);s.content.scrollTop=0;s.buttons.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));});lucide.createIcons();preview(index,index,false);$('#status').textContent=`${labels[index]} · page changée au relâchement.`;}
  function stopDemo(){cancelAnimationFrame(demoFrame);demoFrame=0;states.forEach(s=>s.nav.querySelector('.demo-pointer').hidden=true);$('#demo').disabled=false;}
  $('#demo').onclick=()=>{if(owner)return;stopDemo();commit(0);if(reduce.matches){commit(3);$('#status').textContent='Mouvements réduits : passage direct à Profil.';return;}$('#demo').disabled=true;const start=performance.now(),length=$('#slow').checked?4000:2100;states.forEach(s=>s.nav.querySelector('.demo-pointer').hidden=false);function tick(time){const t=Math.min(1,(time-start)/length),x=3*(t*t*(3-2*t));preview(Math.min(3,Math.round(x)),x,true);states.forEach(s=>s.nav.querySelector('.demo-pointer').style.setProperty('--pointer-x',`${5+(x+.5)*(s.nav.clientWidth-10)/4-13.5}px`));$('#status').textContent='Doigt posé : la page Séries reste affichée pendant le glissement.';if(t<1)demoFrame=requestAnimationFrame(tick);else{stopDemo();commit(3);}}demoFrame=requestAnimationFrame(tick);};
  $('#backdrop').onchange=e=>document.body.classList.toggle('dark',e.target.value==='dark');
  $('#slow').onchange=e=>document.documentElement.style.setProperty('--settle',e.target.checked?'1200ms':'520ms');
  addEventListener('resize',()=>preview(candidate,fraction,!!owner||!!demoFrame));
  document.addEventListener('visibilitychange',()=>{if(document.hidden){stopDemo();owner=null;preview(selected,selected,false);}});
  reduce.addEventListener('change',()=>{stopDemo();owner=null;preview(selected,selected,false);});
  commit(0);$('#status').textContent='Les trois aperçus sont synchronisés pour comparer le même onglet.';
})();
