"""Export the approved ribbon SVGs to Flutter paths and native PNGs.
Requires Pillow only. SVG sources use M/C/Z paths and flat fills; no font needed.
Run from any directory: python3 scripts/build_brand.py
"""
from pathlib import Path
import json
import re
import xml.etree.ElementTree as ET
from PIL import Image, ImageDraw, ImageChops

ROOT = Path(__file__).resolve().parents[1]
BRAND = ROOT / 'app/assets/brand'
NS = '{http://www.w3.org/2000/svg}'


def read_svg(name):
    root = ET.parse(BRAND / name).getroot()
    _, _, width, height = map(float, root.attrib['viewBox'].split())
    layers = []
    for element in root:
        if element.tag == NS + 'rect':
            layers.append(('background', element.attrib['fill']))
        elif element.tag == NS + 'path':
            tokens = re.findall(r'[MCZ]|-?\d+(?:\.\d+)?', element.attrib['d'])
            commands = []
            while tokens:
                op = tokens.pop(0)
                count = {'M': 2, 'C': 6, 'Z': 0}[op]
                commands.append((op, [float(v) for v in tokens[:count]]))
                del tokens[:count]
            layers.append((commands, element.attrib['fill']))
        else:
            raise ValueError(f'Unsupported SVG element: {element.tag}')
    return width, height, layers


def render(name, width, height, padding=0):
    vw, vh, layers = read_svg(name)
    supersampling = 4 if width < 512 else 2
    size = (width * supersampling, height * supersampling)
    scale = min((width - padding * 2) / vw, (height - padding * 2) / vh)
    dx, dy = (width - vw * scale) / 2, (height - vh * scale) / 2
    canvas = Image.new('RGBA', size)
    for commands, color in layers:
        if commands == 'background':
            canvas.paste(color, (0, 0, *size))
            continue
        mask = Image.new('1', size)
        points = []
        current = None
        for op, values in commands:
            if op == 'M':
                current = values
                points = [current]
            elif op == 'C':
                p0 = current
                p1, p2, p3 = values[:2], values[2:4], values[4:]
                for step in range(1, 25):
                    t = step / 24
                    points.append([(1-t)**3*p0[j] + 3*(1-t)**2*t*p1[j]
                                   + 3*(1-t)*t*t*p2[j] + t**3*p3[j] for j in (0, 1)])
                current = p3
            elif op == 'Z':
                contour = Image.new('1', size)
                ImageDraw.Draw(contour).polygon(
                    [((x*scale+dx)*supersampling, (y*scale+dy)*supersampling)
                     for x, y in points], fill=1)
                mask = ImageChops.logical_xor(mask, contour)
        canvas.alpha_composite(Image.composite(Image.new('RGBA', size, color),
                                               Image.new('RGBA', size), mask))
    return canvas.resize((width, height), Image.Resampling.LANCZOS)


def generate_paths():
    pieces = ["// Generated by scripts/build_brand.py from approved SVGs.\n"
              "import 'package:flutter/material.dart';\n"]
    for name, file in [('ribbon', 'symbol-lilac.svg'), ('lockup', 'lockup-lilac.svg')]:
        _, _, layers = read_svg(file)
        for index, (commands, _) in enumerate(layers):
            lines = [f'final {name}Path{index} = Path()..fillType = PathFillType.evenOdd']
            for op, values in commands:
                method = {'M': 'moveTo', 'C': 'cubicTo', 'Z': 'close'}[op]
                lines.append(f'  ..{method}(' + ', '.join(f'{n:.3f}' for n in values) + ')')
            pieces.append('\n'.join(lines) + ';\n')
    (ROOT / 'app/lib/brand/ribbon_paths.dart').write_text('\n'.join(pieces))


def main():
    generate_paths()
    icon = render('app-icon.svg', 1024, 1024).convert('RGB')
    icon.save(BRAND / 'app-icon-1024.png')
    ios = ROOT / 'app/ios/Runner/Assets.xcassets/AppIcon.appiconset'
    for entry in json.loads((ios / 'Contents.json').read_text())['images']:
        size = round(float(entry['size'].split('x')[0]) * float(entry['scale'].rstrip('x')))
        render('app-icon.svg', size, size).convert('RGB').save(ios / entry['filename'])
    for density, size in [('mdpi', 48), ('hdpi', 72), ('xhdpi', 96), ('xxhdpi', 144), ('xxxhdpi', 192)]:
        dest = ROOT / f'app/android/app/src/main/res/mipmap-{density}/ic_launcher.png'
        render('app-icon.svg', size, size).convert('RGB').save(dest)
    # Transparent symbol; the native launch surface supplies its own background.
    launch = render('symbol-lilac.svg', 1024, 1024, padding=192)
    launch.save(ROOT / 'app/assets/images/launch_mark.png')
    launch.save(ROOT / 'app/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png')
    print('Approved ribbon exported: Flutter paths, launcher icons and launch mark.')


if __name__ == '__main__':
    main()
