'use strict';
// Original prototype inspired by NumberFlow's per-digit continuity and Vaul's
// momentum-based drawer. No source or dependencies copied from either library.
const springStates=[];
function spring(initial,stiffness=360,damping=32){const s={x:initial,target:initial,v:0,stiffness,damping};springStates.push(s);return s;}
const units=spring(24),tens=spring(20),width=spring(27),rulerPosition=spring(4,400,34);
let frame=0,lastTime=0,reelValue=4,dragRuler=null;
const reels=[];$('#digits').replaceChildren();
for(let i=0;i<2;i++){const el=document.createElement('span');el.className='reel';const faces=[];for(let j=-2;j<=2;j++){const face=document.createElement('span');face.className='reel-face';el.append(face);faces.push(face);}$('#digits').append(el);reels.push({el,faces,state:i===0?tens:units});}
function draw(){const dual=(width.x-27)/27;reels.forEach((r,index)=>{const isTens=index===0;r.el.style.transform=`translateX(${isTens?-width.x/2:width.x/2-27}px)`;r.el.style.opacity=isTens?Math.max(0,Math.min(1,dual)):1;const base=Math.round(r.state.x);r.faces.forEach((face,i)=>{const digit=base+i-2,offset=digit-r.state.x;face.textContent=((digit%10)+10)%10;face.style.transform=`translateY(${offset*47}px) rotateX(${-offset*35}deg)`;face.style.opacity=Math.max(0,1-Math.pow(Math.abs(offset)/1.6,2));});});$('#ruler-track').style.transform=`translateX(${-(rulerPosition.x-1)*28}px)`;}
function tick(time){const dt=Math.min((time-lastTime)/1000||.016,.032);lastTime=time;let moving=false;for(const s of springStates){if(reduced()){s.x=s.target;s.v=0;}else{const acceleration=(s.target-s.x)*s.stiffness-s.v*s.damping;s.v+=acceleration*dt;s.x+=s.v*dt;}if(Math.abs(s.target-s.x)<.002&&Math.abs(s.v)<.02){s.x=s.target;s.v=0;}else moving=true;}draw();if(moving)frame=requestAnimationFrame(tick);else{frame=0;lastTime=0;}}
function wake(){if(!frame)frame=requestAnimationFrame(tick);}
function targetDigit(state,digit,dir){const old=((Math.round(state.target)%10)+10)%10;if(old===digit)return;let distance=digit-old;if(dir>0&&distance<0)distance+=10;if(dir<0&&distance>0)distance-=10;state.target+=distance;}
numberView=function(n,direction=0){if(!Number.isInteger(Number(n))||n===''){return;}const integer=Number(n);if(integer<1||integer>12)return;const dir=Math.sign(integer-reelValue);if(direction){targetDigit(units,integer%10,dir);targetDigit(tens,Math.floor(integer/10),dir);}else{units.x=units.target=20+integer%10;units.v=0;tens.x=tens.target=20+Math.floor(integer/10);tens.v=0;}reelValue=integer;width.target=integer>=10?54:27;if(!direction)width.x=width.target;if(!dragRuler)rulerPosition.target=integer;$('#ruler').setAttribute('aria-valuenow',integer);$('#ruler').setAttribute('aria-valuetext',`Épisode ${integer}`);document.querySelectorAll('.tick').forEach((t,i)=>t.classList.toggle('active',i+1===integer));wake();};
$('#ruler-track').innerHTML=episodes.map((_,i)=>`<span class="tick" aria-hidden="true">${i+1}</span>`).join('');
// Scale the physical spring's time without changing its final value.
const baseTick=tick;
tick=function(time){if($('#slow').checked&&!reduced()){for(const s of springStates){s.stiffness=s===rulerPosition?44.44:40;s.damping=s===rulerPosition?11.33:10.67;}}else{for(const s of springStates){s.stiffness=s===rulerPosition?400:360;s.damping=s===rulerPosition?34:32;}}baseTick(time);};
const ruler=$('#ruler');
ruler.addEventListener('pointerdown',e=>{if(e.button!==0)return;dragRuler={id:e.pointerId,start:e.clientX,initial:value,moved:false};ruler.setPointerCapture(e.pointerId);ruler.focus({preventScroll:true});});
ruler.addEventListener('pointermove',e=>{if(!dragRuler||e.pointerId!==dragRuler.id)return;const delta=(dragRuler.start-e.clientX)/28;if(Math.abs(delta)>.15)dragRuler.moved=true;const raw=Math.max(1,Math.min(12,dragRuler.initial+delta));rulerPosition.x=rulerPosition.target=raw;rulerPosition.v=0;const n=Math.round(raw);if(n!==value)select(n);wake();});
function endRuler(e){if(!dragRuler||e.pointerId!==dragRuler.id)return;if(!dragRuler.moved){const box=ruler.getBoundingClientRect();select(Math.max(1,Math.min(12,value+Math.round((e.clientX-(box.left+box.width/2))/28))));}dragRuler=null;rulerPosition.target=value;wake();}
ruler.addEventListener('pointerup',endRuler);ruler.addEventListener('pointercancel',()=>{dragRuler=null;rulerPosition.target=value;wake();});ruler.addEventListener('keydown',e=>{let n=value;if(e.key==='ArrowRight')n++;else if(e.key==='ArrowLeft')n--;else if(e.key==='Home')n=1;else if(e.key==='End')n=12;else return;e.preventDefault();select(Math.max(1,Math.min(12,n)));});
const bg=$('.app-background');
function backTransform(progress){return `translateY(${progress*12}px) scale(${1-progress*.055})`;}
function setBackground(progress){bg.style.transform=backTransform(progress);bg.style.borderRadius=`${progress*25}px`;}
function backgroundMotion(from,to,ms){setBackground(to);animate(bg,[{transform:backTransform(from),borderRadius:`${from*25}px`},{transform:backTransform(to),borderRadius:`${to*25}px`}],ms);}
const simpleShow=show,simpleHide=hide;
show=function(){simpleShow();backgroundMotion(0,1,500);const sheet=$('#sheet');animate(sheet,[{transform:'translateY(105%)'},{transform:'translateY(0)'}],500).effect.updateTiming({easing:'cubic-bezier(.32,.72,0,1)'});const children=[$('.sheet-heading'),$('.season'),$('.stepper'),$('.ruler'),$('.preview'),$('#confirm')];children.forEach((el,i)=>{animate(el,[{opacity:0,transform:'translateY(10px)'},{opacity:1,transform:'translateY(0)'}],320).effect.updateTiming({delay:duration(65+i*22),fill:'backwards'});});};
hide=function(){simpleHide();backgroundMotion(1,0,300);};
$('#open').onclick=show;$('#close').onclick=hide;$('#scrim').onclick=hide;$('#back').onclick=show;$('#choose-again').onclick=show;$('#replay').onclick=()=>{select(9,false);show();};
let sheetDrag=null;const handle=$('#handle'),sheet=$('#sheet');
handle.addEventListener('pointerdown',e=>{if(e.button!==0)return;sheet.getAnimations().forEach(a=>a.cancel());bg.getAnimations().forEach(a=>a.cancel());sheetDrag={id:e.pointerId,y:e.clientY,lastY:e.clientY,lastTime:performance.now(),velocity:0,delta:0};handle.setPointerCapture(e.pointerId);});
handle.addEventListener('pointermove',e=>{if(!sheetDrag||sheetDrag.id!==e.pointerId)return;const now=performance.now();sheetDrag.velocity=(e.clientY-sheetDrag.lastY)/Math.max(8,now-sheetDrag.lastTime);sheetDrag.lastTime=now;sheetDrag.lastY=e.clientY;const distance=e.clientY-sheetDrag.y;sheetDrag.delta=distance<0?distance*.15:distance;sheet.style.transform=`translateY(${sheetDrag.delta}px)`;const progress=1-Math.min(1,Math.max(0,distance)/sheet.offsetHeight);setBackground(progress);$('#scrim').style.opacity=progress;});
function releaseSheet(e){if(!sheetDrag||sheetDrag.id!==e.pointerId)return;const d=sheetDrag.delta;const shouldClose=e.type!=='pointercancel'&&(d>100||(d>20&&sheetDrag.velocity>.65));sheetDrag=null;sheet.style.transform='';$('#scrim').style.opacity='';if(shouldClose){simpleHide();const closing=sheet.getAnimations()[0];if(closing){closing.effect.setKeyframes([{transform:`translateY(${d}px)`},{transform:`translateY(${sheet.offsetHeight+20}px)`}]);closing.effect.updateTiming({duration:duration(250)});}backgroundMotion(Math.max(0,1-d/sheet.offsetHeight),0,250);}else{animate(sheet,[{transform:`translateY(${d}px)`},{transform:'translateY(0)'}],380);backgroundMotion(Math.max(0,1-d/sheet.offsetHeight),1,380);}}
handle.addEventListener('pointerup',releaseSheet);handle.addEventListener('pointercancel',releaseSheet);
$('#reduced').addEventListener('change',wake);select(9,false);show();
