'use strict';
const $=s=>document.querySelector(s);
const episodes=['La tant attendue Elbaph ! Retrouvailles et banquet géant !','La confusion de Nami ! Aventure au pays des blocs !','Le mystère du pays des blocs','Détruis le jardin miniature ! Évasion du pays des blocs !','Un nouveau cap','La promesse','Les retrouvailles','Le passage','À contre-courant','Au-delà de la frontière','L’autre rive','L’aube'];
let value=4, isOpen=false, lastFocus=null;
const reduced=()=>$('#reduced').checked||matchMedia('(prefers-reduced-motion: reduce)').matches;
const duration=ms=>reduced()?0:ms*($('#slow').checked?3:1);
function animate(el,frames,ms){el.getAnimations().forEach(a=>a.cancel());const a=el.animate(frames,{duration:duration(ms),easing:'cubic-bezier(.2,.75,.2,1)'});a.finished.catch(()=>{});return a;}
function numberView(n,direction=0){const root=$('#digits');const old=root.lastElementChild;root.querySelectorAll('.outgoing').forEach(e=>e.remove());const item=document.createElement('span');item.className='digit';item.textContent=n;root.append(item);
 if(old){old.classList.add('outgoing');animate(old,[{opacity:1,transform:'translateY(0)'},{opacity:0,transform:`translateY(${-direction*30}px)`}],180).finished.then(()=>old.remove()).catch(()=>old.remove());}
 if(direction)animate(item,[{opacity:0,transform:`translateY(${direction*30}px)`},{opacity:1,transform:'translateY(0)'}],240);
}
function preview(error=false, direction=0){const root=$('#preview');root.classList.toggle('error',error);const old=root.lastElementChild;root.querySelectorAll('.outgoing').forEach(e=>e.remove());const copy=document.createElement('div');copy.className='preview-copy';const label=document.createElement('p');label.className='label';label.textContent=error?'Numéro indisponible':`Épisode ${value}`;const title=document.createElement('p');title.className='title';title.textContent=error?'Choisis un numéro entre 1 et 12.':episodes[value-1];copy.append(label,title);root.append(copy);
 if(old){old.classList.add('outgoing');old.setAttribute('aria-hidden','true');animate(old,[{opacity:1},{opacity:0}],110).finished.then(()=>old.remove()).catch(()=>old.remove());}
 if(direction)animate(copy,[{opacity:0,transform:`translateY(${direction*5}px)`},{opacity:1,transform:'translateY(0)'}],200);
}
function select(n,animated=true){const previous=value;value=n;$('#number').value=n;numberView(n,animated?Math.sign(n-previous):0);preview(false,animated?Math.sign(n-previous):0);$('#previous').disabled=n===1;$('#next').disabled=n===episodes.length;}
function commit(){const text=$('#number').value.trim();const n=Number(text);if(!/^\d+$/.test(text)||n<1||n>episodes.length){preview(true);return false;}select(n,false);return true;}
function show(){lastFocus=document.activeElement;$('#detail').hidden=true;const sheet=$('#sheet'),scrim=$('#scrim');isOpen=true;sheet.inert=false;sheet.classList.add('visible');scrim.classList.add('visible');animate(sheet,[{transform:'translateY(105%)'},{transform:'translateY(0)'}],380);animate(scrim,[{opacity:0},{opacity:1}],280);$('#close').focus({preventScroll:true});}
function hide(){if(!isOpen)return;isOpen=false;$('#number').blur();$('#sheet').inert=true;const animation=animate($('#sheet'),[{transform:'translateY(0)'},{transform:'translateY(105%)'}],240);animate($('#scrim'),[{opacity:1},{opacity:0}],200);animation.finished.then(()=>{if(!isOpen){$('#sheet').classList.remove('visible');$('#scrim').classList.remove('visible');lastFocus?.focus({preventScroll:true});}}).catch(()=>{});}
for(const [id,delta] of [['previous',-1],['next',1]]){$('#'+id).addEventListener('click',()=>select(Math.max(1,Math.min(episodes.length,value+delta))));}
for(const button of document.querySelectorAll('.step')){button.addEventListener('pointerdown',e=>{e.preventDefault();if(!button.disabled)animate(button,[{transform:'scale(1)'},{transform:'scale(.87)'}],90).effect.updateTiming({fill:'forwards'});});const release=()=>animate(button,[{transform:'scale(.87)'},{transform:'scale(1.03)',offset:.7},{transform:'scale(1)'}],220);button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release);button.addEventListener('pointerleave',()=>{if(button.getAnimations().length)release();});}
$('#number').addEventListener('focus',()=>$('#number').select());$('#number').addEventListener('input',()=>{const n=Number($('#number').value);if(/^\d+$/.test($('#number').value)&&n>=1&&n<=episodes.length){value=n;preview();$('#previous').disabled=n===1;$('#next').disabled=n===episodes.length;}else preview(true);});$('#number').addEventListener('blur',()=>{if(!commit())numberView($('#number').value||'—');});$('#number').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();if(commit())$('#number').blur();}});
$('#confirm').addEventListener('click',()=>{if(!commit())return;$('#detail-number').textContent=`Épisode ${value}`;$('#detail-title').textContent=episodes[value-1];$('#detail').hidden=false;animate($('#detail'),[{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],280);$('#back').focus({preventScroll:true});});
$('#replay').onclick=()=>{select(4,false);show();};$('#open').onclick=show;$('#close').onclick=hide;$('#scrim').onclick=hide;$('#back').onclick=show;$('#choose-again').onclick=show;
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#detail').hidden)show();else hide();}if(e.key==='Tab'&&isOpen&&$('#detail').hidden&&$('#sheet').contains(document.activeElement)){const nodes=[...$('#sheet').querySelectorAll('button,input')].filter(x=>!x.disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
$('#reduced').addEventListener('change',()=>{if(reduced())document.getAnimations().forEach(a=>a.finish());});select(4,false);show();
